import type { CharacterArchetype } from '../host/character-profile.js';
import type { AdventureAction, AdventureGame, AdventureOptions, AdventureSnapshot, Position, ThreatView, PlaceView } from './adventure-types.js';
const p=(x=0,y=0,z=0):Position=>({x,y,z}); const d=(a:Position,b:Position)=>Math.hypot(a.x-b.x,a.z-b.z);
type Mutable<T> = { -readonly [K in keyof T]: T[K] };
type Threat = Mutable<ThreatView> & { timer:number };
const places:PlaceView[]=[{id:'town',name:'Frostwood Camp',position:p(0,0,-8),kind:'town'},{id:'gate',name:'Thicket Gate',position:p(0,0,0),kind:'gate'},{id:'cores',name:'Frost Cores',position:p(-2,0,12),kind:'resource'},{id:'ritual',name:'Old Ritual Stone',position:p(2,0,40),kind:'ritual'},{id:'mara',name:'Mara',position:p(3.4,0,-7.5),kind:'shop'}];
export function createAdventure(options:AdventureOptions={}):AdventureGame {
 let phase:'town'|'expedition'|'lost'='town', archetype=options.archetype??'warrior', pos=p(0,0,-8), cam=p(0,0,1), health=100, supplies=15,cargo=0,potions=0,relics=0,banked=0,resource=6,presence=0, ritualCalled=false,shopOpen=false, cooldown=0,guard=0,jump=0,selected='scout',seq=0; const held=new Set<AdventureAction>(); let mouse=false;
 const threats:Threat[]=['scout','nest','warder','patrol','ritual-guardian'].map((id,i)=>({id,name:['Frost Scout','Thorn Nest','Bark Warder','Frost Patrol','Ritual Guardian'][i],position:[p(-2,0,8),p(-8,0,16),p(4,0,22),p(8,0,30),p(2,0,40)][i],health:[12,18,28,20,48][i],maximumHealth:[12,18,28,20,48][i],active:i<4,selected:id===selected,phase:'dormant',timer:0,remainingSeconds:0,phaseDuration:3,preparation:'',intention:'',damage:[8,10,12,10,18][i],reach:3.5,benefit:'',actionSequence:0,lastActionHit:false,targetPosition:p(),}));
 let report='Ready at Frostwood Camp.';
 function snapshot():AdventureSnapshot { return {selectedThreat:selected,phase,player:{position:pos,cameraForward:cam,archetype,health,maximumHealth:100,grounded:jump<=0,moving:held.has('forward')||held.has('backward')||held.has('left')||held.has('right')||mouse,backpedaling:held.has('backward')&&!mouse,attackSequence:seq,actionCooldown:cooldown,guardSeconds:guard},threats:threats.map(t=>({...t,selected:t.id===selected,remainingSeconds:Math.max(0,t.timer)})),places,supplies,cargo,resourceRemaining:resource,potions,carriedRelics:relics,bankedRelics:banked,presence,ritualCalled,shopOpen,potionPrice:3,potionHealing:35,report}; }
 function near(x: Position | PlaceView,r=4){return d(pos,"position" in x ? x.position : x)<=r;}
 function strike(){if(phase!=='expedition'||cooldown>0)return; cooldown=2; seq++; const t=threats.find(t=>t.id===selected&&t.active&&near(t.position,3.5)); if(t){t.health=Math.max(0,t.health-9);t.actionSequence++; if(!t.health){t.active=false;t.phase='cleared';t.benefit='cleared';presence++;report=`${t.name} defeated.`;}}}
 function interact(a:AdventureAction){if(a==='buyPotion'&&near(places[4])&&supplies>=3){supplies-=3;potions++;shopOpen=true;report='Mara sold you a health potion.';} else if(a==='drinkPotion'&&potions>0&&health<100){potions--;health=Math.min(100,health+35);} else if(a==='rest'&&near(places[0])){health=100;report='You rest at camp.';} else if(a==='gather'&&near(places[2])&&resource>0&&cooldown<=0){resource--;cargo++;cooldown=2; if(threats[2].active)health=Math.max(0,health-8);report='Frost core gathered.';} else if(a==='ritual'&&near(places[3])&&cargo>=6){cargo-=6;ritualCalled=true;threats[4].active=true;report='The ritual guardian awakens.';} else if(a==='interact'&&near(places[1])&&phase==='town'){phase='expedition';report='You enter the Frostwood.';} else if(a==='interact'&&near(places[0])&&phase==='expedition'){phase='town';banked+=relics;relics=0;report='You return safely; cargo and relics banked.';}}
 function edge(a:AdventureAction){if(a==='strike')strike(); else if(a==='brace')guard=3; else if(a==='jump'&&jump<=0)jump=1; else if(a==='gather'||a==='ritual'||a==='interact'||a==='buyPotion'||a==='drinkPotion'||a==='rest')interact(a); else if(a==='target'){const i=threats.findIndex(t=>t.id===selected); selected=threats[(i+1)%threats.length].id;} }
 const game:AdventureGame={get snapshot(){return snapshot();},start(){},advance(dt){const x=Math.min(dt,.1); cooldown=Math.max(0,cooldown-x);guard=Math.max(0,guard-x);jump=Math.max(0,jump-x); if(phase==='lost')return; let f=mouse?1:(held.has('forward')?1:0)-(held.has('backward')?1:0),s=(held.has('right')?1:0)-(held.has('left')?1:0); if(held.has('left')&&held.has('right'))s=0; const n=Math.hypot(f,s)||1; pos={x:pos.x+(cam.x*f-cam.z*s)/n*4.5*x,y:pos.y,z:pos.z+(cam.z*f+cam.x*s)/n*4.5*x}; if(phase==='expedition'){for(const t of threats){if(!t.active)continue;const q=d(pos,t.position);if(q<8&&t.phase==='dormant'){t.phase='preparation';t.timer=3;t.preparation='3 second warning';t.intention='Preparing a strike';}if(t.phase==='preparation'){t.timer-=x;if(t.timer<=0){t.phase='action';t.timer=.35;t.targetPosition=pos;t.intention='Strike incoming';}}else if(t.phase==='action'){t.timer-=x;if(t.timer<=0){t.actionSequence++;t.lastActionHit=d(pos,t.targetPosition)<=t.reach;if(t.lastActionHit)health=Math.max(0,health-(guard>0?t.damage/2:t.damage));t.phase='recovery';t.timer=2.65;}}else if(t.phase==='recovery'){t.timer-=x;if(t.timer<=0)t.phase='dormant';}} if(health<=0){phase='lost';report='You were lost in the Frostwood.';}}},setAction(a,on){if(on&&!held.has(a))edge(a);on?held.add(a):held.delete(a);},setMouseForward(on){mouse=on;},setCameraForward(x,z){const n=Math.hypot(x,z)||1;cam=p(x/n,0,z/n);},selectTarget(id){if(threats.some(t=>t.id===id))selected=id;},save(){return JSON.stringify({version:1,phase,archetype,pos,cam,health,supplies,cargo,potions,relics,banked,resource,presence,ritualCalled});}};
 if(options.save){const s=JSON.parse(options.save) as Record<string,unknown>; if(s.version!==1||typeof s.health!=='number'||typeof s.supplies!=='number')throw new Error('invalid adventure save'); phase=s.phase as typeof phase; archetype=s.archetype as CharacterArchetype; pos=s.pos as Position;cam=s.cam as Position;health=s.health;supplies=s.supplies;cargo=s.cargo as number;potions=s.potions as number;relics=s.relics as number;banked=s.banked as number;resource=s.resource as number;presence=s.presence as number;ritualCalled=s.ritualCalled as boolean; }
 return game;
}
