use super::*;

impl Default for Tuning {
    fn default() -> Self {
        Self {
            move_speed: 4.5,
            gather_yield: 3.0,
            gather_presence: 4.0,
            gather_cooldown: 2.0,
            gather_damage: 8.0,
            resource_per_expedition: 12.0,
            ritual_cost: 6.0,
            ritual_presence: 12.0,
            ritual_cooldown: 1.0,
            passive_presence: 0.1,
            movement_presence: 0.4,
            party_movement_presence: 0.04,
            strike_presence: 1.0,
            party_strike_presence: 0.1,
            base_strike_cooldown: 2.0,
            party_damage: 4.0,
            relic_damage: 4.0,
            brace_cooldown: 1.0,
            brace_duration: 3.0,
            guard_multiplier: 0.5,
            intent_duration: 3.0,
            action_duration: 0.35,
            jump_speed: 5.5,
            gravity: 14.0,
            potion_price: 3.0,
            potion_healing: 30.0,
        }
    }
}
impl Default for Game {
    fn default() -> Self {
        Self::new()
    }
}
impl Game {
    pub fn new() -> Self {
        let body_parts = [
            ("head", "Head", "head-kind", 1.0),
            ("torso", "Torso", "torso-kind", 1.0),
            ("back", "Back", "back-kind", 3.0),
            ("left-arm", "Left arm", "arm-kind", 1.0),
            ("right-arm", "Right arm", "arm-kind", 1.0),
            ("legs", "Legs", "legs-kind", 1.0),
        ]
        .into_iter()
        .map(|(id, label, kind, slot_capacity)| BodyPart {
            id: id.into(),
            label: label.into(),
            owner: "wayfarer".into(),
            kind: kind.into(),
            health: 100.0,
            maximum_health: 100.0,
            slot_capacity,
        })
        .collect();
        let components = [
            (
                "ember-core",
                "Ember heart",
                "back-kind",
                Some("back"),
                "ember-core",
                100.0,
                8.0,
                10.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
            ),
            (
                "drive",
                "Powered leg braces",
                "legs-kind",
                Some("legs"),
                "ember-core",
                80.0,
                7.0,
                0.0,
                4.0,
                36.0,
                0.0,
                0.0,
                0.0,
            ),
            (
                "lance",
                "Sun lance",
                "arm-kind",
                Some("right-arm"),
                "drive",
                45.0,
                5.0,
                0.0,
                8.0,
                0.0,
                9.0,
                0.0,
                0.0,
            ),
            (
                "cooler",
                "Mist vanes",
                "back-kind",
                Some("back"),
                "ember-core",
                50.0,
                4.0,
                0.0,
                3.0,
                0.0,
                0.0,
                7.0,
                0.0,
            ),
            (
                "armor",
                "Iron mantle",
                "torso-kind",
                None,
                "ember-core",
                100.0,
                14.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                3.0,
            ),
            (
                "auxiliary-core",
                "Reserve ember heart",
                "back-kind",
                None,
                "ember-core",
                80.0,
                8.0,
                6.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
            ),
            (
                "helmet",
                "Ashguard helmet",
                "head-kind",
                None,
                "ember-core",
                65.0,
                3.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                4.0,
            ),
        ]
        .into_iter()
        .map(
            |(
                id,
                label,
                kind,
                part,
                upstream,
                health,
                mass,
                generation,
                draw,
                thrust,
                firepower,
                cooling,
                protection,
            )| Component {
                id: id.into(),
                label: label.into(),
                accepted_kind: kind.into(),
                attached_to: part.map(str::to_owned),
                linked: true,
                upstream: upstream.into(),
                health,
                maximum_health: health,
                mass,
                generation,
                draw,
                thrust,
                firepower,
                cooling,
                protection,
            },
        )
        .collect();
        let threats = [
            (
                "scout",
                "Briar lookout",
                [-3.0, 10.0],
                18.0,
                true,
                "Listening for footsteps",
                "Sounding the alarm",
                0.0,
                3.0,
                35.0,
                "Clear the lookout to stop its repeated alarms.",
            ),
            (
                "nest",
                "Thorn nest",
                [5.0, 20.0],
                24.0,
                true,
                "Rousing the swarm",
                "Swarm rush",
                7.0,
                0.0,
                3.0,
                "Clear the nest to open the east path through the thicket.",
            ),
            (
                "warder",
                "Root warder",
                [-3.0, 30.0],
                30.0,
                true,
                "Raising thorn wards",
                "Thorn lash",
                8.0,
                0.0,
                5.0,
                "Clear the warder to gather frost cores without cutting thorns.",
            ),
            (
                "patrol",
                "Ash hound patrol",
                [3.0, 35.0],
                36.0,
                true,
                "Sweeping the trail",
                "Charging the company",
                10.0,
                0.0,
                7.0,
                "Clear the patrol to prevent ambushes during retreat.",
            ),
            (
                "ritual-guardian",
                "Called frost guardian",
                [2.0, 40.0],
                48.0,
                false,
                "Drawing a freezing breath",
                "Frost torrent",
                20.0,
                0.0,
                3.0,
                "Defeat the deliberately called guardian, then extract its frost relic.",
            ),
        ]
        .into_iter()
        .map(
            |(
                id,
                name,
                position,
                health,
                active,
                preparation,
                action,
                damage,
                noise,
                reach,
                benefit,
            )| Threat {
                id: id.into(),
                name: name.into(),
                position,
                health,
                maximum_health: health,
                active,
                intent_stage: 0,
                intent_remaining: 3.0,
                intent_preparation: preparation.into(),
                intent_action: action.into(),
                intent_damage: damage,
                intent_noise: noise,
                intent_reach: reach,
                benefit: benefit.into(),
                action_sequence: 0,
                last_action_hit: false,
                last_action_target: [0.0, -8.0],
            },
        )
        .collect();
        let places = [
            ("hearthstead", "Hearthstead", [0.0, -8.0]),
            ("forest-gate", "North gate / return to safety", [0.0, 0.0]),
            ("frost-cores", "Frost cores / G to gather", [-2.0, 12.0]),
            (
                "ritual-site",
                "Deep grove / R to offer six cores",
                [2.0, 40.0],
            ),
            ("mara", "Mara / Apothecary / F to talk", [3.4, -7.5]),
        ]
        .into_iter()
        .map(|(id, name, position)| Place {
            id: id.into(),
            name: name.into(),
            position,
        })
        .collect();
        Self {
            ticks: 0,
            status: String::new(),
            phase: "Workshop".into(),
            position: [0.0, -8.0],
            stock: 15.0,
            cargo: 0.0,
            report: "Walk through Hearthstead’s north gate. Gather frost cores and return alive."
                .into(),
            fit_report: "Choose equipment, then choose a compatible body part.".into(),
            selected_component: "lance".into(),
            creature_name: "Wayfarer".into(),
            baseline_speed: 1.4,
            body_mass: 28.0,
            retreat_condition: 60.0,
            body_parts,
            components,
            capacity_readings: Capacity {
                mass: 24.0,
                power: 10.0,
                drive: 36.0,
                weapon: 9.0,
                cooling: 7.0,
                drive_draw: 4.0,
                weapon_draw: 8.0,
                cooling_draw: 3.0,
            },
            presence: 0.0,
            party_size: 1,
            connected: true,
            resource_remaining: 12.0,
            ritual_called: false,
            carried_relics: 0.0,
            banked_relics: 0.0,
            action_cooldown: 0.0,
            guard_remaining: 0.0,
            selected_threat: "scout".into(),
            threats,
            places,
            movement: [0.0, 0.0],
            move_remaining: 0.0,
            elevation: 0.0,
            vertical_speed: 0.0,
            potions: 0.0,
            shop_open: false,
            shop_status: "Mara sells health potions beside the Hearthstead road.".into(),
            tuning: Tuning::default(),
        }
    }
}
