import { terrainHeight } from './cave-layout.js';
import type { ThreatDefinition } from './adventure.js';

const point = (x: number, z: number) => ({ x, y: terrainHeight(x,z), z });
const patrol = (x: number, z: number) => [point(x,z),point(x+2,z+2),point(x+4,z),point(x+2,z-2)];

export const REGIONAL_THREATS = [
  { id: 'glassmire-lantern', name: 'Mire Lantern', level: 3, behavior: 'head', position: point(20,143), health: 108,
    disposition: 'hostile', aggroRange: 6, leash: 15, speed: 1.5, patrol: patrol(20,143),
    preparation: 'Drawing light from the pools', intention: 'Fireball', damage: 8, reach: 10, salvage: 2,
    description: 'An old survey mind burns inside a floating skull of green glass. Its light guides travellers into the mire.',
    benefit: 'Recover two pieces of alchemical salvage and quiet the western pools.' },
  { id: 'glassmire-stalker', name: 'Mercury Hound', level: 3, behavior: 'wolf', position: point(56,155), health: 96,
    disposition: 'hostile', aggroRange: 6, leash: 20, speed: 3.6, patrol: patrol(56,155),
    preparation: 'Coiling its silver limbs', intention: 'Lunging Maul', damage: 18, reach: 2, salvage: 2,
    description: 'A feral courier animal with mercury in its veins and a broken delivery order in its skull.',
    benefit: 'Search its metal hide for two pieces of salvage.' },
  { id: 'glassmire-grazer', name: 'Verdigris Grazer', level: 2, position: point(8,178), health: 66,
    disposition: 'neutral', aggroRange: 0, callsForHelp: false, leash: 12, speed: .7, pursuitSpeed: 2, patrol: patrol(8,178),
    preparation: 'Raising its mossy pincers', intention: 'Reedbreaker', damage: 12, reach: 2.5,
    description: 'An ancient ditch-tender grazes on glass reeds. It will leave you alone if you leave its work alone.',
    benefit: 'A peaceful ditch-tender feeding among the glass reeds.' },
  { id: 'choir-cantor', name: 'Broken Cantor', level: 5, behavior: 'head', position: point(187,-42), health: 144,
    disposition: 'hostile', aggroRange: 7, leash: 18, speed: 1.6, patrol: patrol(187,-42),
    preparation: 'Singing through cracked valves', intention: 'Fireball', damage: 8, reach: 10, salvage: 3,
    description: 'One voice of the Choir Engine, torn free of its cooling rack. It answers every living voice with fire.',
    benefit: 'Recover three pieces of machine salvage from its shattered valves.' },
  { id: 'choir-hound', name: 'Choir Hound', level: 4, behavior: 'wolf', position: point(171,-8), health: 120,
    disposition: 'hostile', aggroRange: 7, leash: 23, speed: 4, patrol: patrol(171,-8),
    preparation: 'Listening for the next note', intention: 'Lunging Maul', damage: 18, reach: 2, salvage: 3,
    description: 'The Choir has replaced this hunter’s nerves with singing wire. Its leaping attacks can be baited into other creatures.',
    benefit: 'Recover three pieces of salvage from the wire-bound hunter.' },
  { id: 'choir-sacristan', name: 'Hollow Sacristan', level: 5, position: point(219,-19), health: 210,
    disposition: 'hostile', aggroRange: 7, leash: 16, speed: 1.5, pursuitSpeed: 3, patrol: patrol(219,-19),
    preparation: 'Winding a broken knee', intention: 'Bellringer Kick', damage: 30, reach: 3.5, salvage: 4,
    description: 'A cathedral attendant still polishes the dead engine with the bones of trespassers. Its slow, heavy kick leaves time to retreat.',
    benefit: 'Four pieces of machine salvage remain inside its silent chest.' },
  { id: 'ossuary-king', name: 'Ossuary Gardener', level: 5, position: point(99,224), health: 180,
    disposition: 'hostile', aggroRange: 6, leash: 16, speed: 1.4, pursuitSpeed: 2.8, patrol: patrol(99,224),
    preparation: 'Drawing back an ivory fist', intention: 'Gravebloom Crush', damage: 28, reach: 3.8, salvage: 4,
    description: 'A colony of pale fungi wears the shape of a groundskeeper. It cultivates the old cooling towers with patient violence.',
    benefit: 'Recover four pieces of salvage from the roots beneath its crown.' },
  { id: 'ossuary-wing', name: 'Mourning Wing', level: 4, position: point(129,195), health: 90,
    disposition: 'hostile', aggroRange: 6, leash: 18, speed: 2.2, pursuitSpeed: 4.5, patrol: patrol(129,195),
    preparation: 'Folding its bone-white wings', intention: 'Memory Bite', damage: 22, reach: 2.2, salvage: 2,
    description: 'A pale scavenger carries old human lullabies in its throat. It bites when the song ends.',
    benefit: 'Recover two pieces of salvage caught in its wire-lined nest.' },
  { id: 'brinewood-bee', name: 'Copper Orchard Bee', level: 3, position: point(-85,139), health: 84,
    disposition: 'neutral', aggroRange: 0, callsForHelp: false, leash: 13, speed: 1.1, pursuitSpeed: 3.8, patrol: patrol(-85,139),
    preparation: 'Fanning its copper wings', intention: 'Vitriol Sting', damage: 17, reach: 2.5, salvage: 2,
    description: 'A brass-pollened bee tends the alchemists’ orchard. Disturbing it turns a quiet harvest into a painful lesson.',
    benefit: 'The orchard bee remains peaceful unless attacked.' },
  { id: 'suture-scavenger', name: 'Little Mender', level: 1, critter: true, position: point(186,141), health: 30,
    disposition: 'neutral', aggroRange: 0, callsForHelp: false, leash: 9, speed: .65, pursuitSpeed: 1.1, patrol: patrol(186,141),
    preparation: 'Opening its little tool-claws', intention: 'Tool-claw Pinch', damage: 3, reach: 1.4,
    description: 'A village scavenger searches for screws, bottle caps and useful bones. It refuses to acknowledge the end of the world.',
    benefit: 'A peaceful scavenger gathering parts for the village.' },
] satisfies readonly ThreatDefinition[];
