[package]
name = "greywrought-clause"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
clause-package = { path = "/home/tom/code/clause/pins/419140bd932bdd8461deb51c9f6c42a4bb5683b1/crates/clause-package" }
clause-runtime = { path = "/home/tom/code/clause/pins/419140bd932bdd8461deb51c9f6c42a4bb5683b1/crates/clause-runtime" }
clause-workbench = { path = "/home/tom/code/clause/pins/419140bd932bdd8461deb51c9f6c42a4bb5683b1/crates/clause-workbench" }

[lints.rust]
unsafe_code = "forbid"
