[package]
name = "greywrought-clause"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
clause-package = { path = "/home/tom/code/clause/pins/f1f5a13fd5cd52bdf85c984a82a6953add33ef18/crates/clause-package" }
clause-runtime = { path = "/home/tom/code/clause/pins/f1f5a13fd5cd52bdf85c984a82a6953add33ef18/crates/clause-runtime" }
clause-workbench = { path = "/home/tom/code/clause/pins/f1f5a13fd5cd52bdf85c984a82a6953add33ef18/crates/clause-workbench" }

[lints.rust]
unsafe_code = "forbid"
