import { check, openBrowser } from "./session.js";

const page = await openBrowser("expedition");
const held = new Set<string>();
async function hold(desired: readonly string[]) {
  for (const code of held) if (!desired.includes(code)) { await page.key(code, false); held.delete(code); }
  for (const code of desired) if (!held.has(code)) { await page.key(code, true); held.add(code); }
}
async function moveTo(x: number, z: number, tolerance = 0.5) {
  const deadline = performance.now() + 18_000;
  while (performance.now() < deadline) {
    const state = await page.read();
    check(state.gamePhase !== "lost", "Character fell while walking the route");
    const dx = x - Number(state.gamePlayerX), dz = z - Number(state.gamePlayerZ);
    if (Math.hypot(dx, dz) <= tolerance) { await hold([]); return; }
    const next: string[] = [];
    // Initial camera faces north (+z), putting world +x to the player's left.
    if (Math.abs(dx) > tolerance / 2) next.push(dx > 0 ? "KeyA" : "KeyD");
    if (Math.abs(dz) > tolerance / 2) next.push(dz > 0 ? "KeyW" : "KeyS");
    await hold(next);
    await Bun.sleep(100);
  }
  throw new Error(`Could not reach ${x},${z}: ${JSON.stringify(await page.read())}`);
}
try {
  await page.enter();
  await page.waitFor('[...document.querySelectorAll("#player-frame img, #target-frame img")].every(image => image.complete && image.naturalWidth > 0)');
  await page.press("KeyL");
  await page.waitFor('!document.getElementById("lorebook-panel").hidden');
  for (const id of ["scout", "patrol", "nest", "warder", "ritual-guardian"]) {
    await page.click('#lorebook-panel button[data-monster-id="' + id + '"]');
    await page.waitFor('document.getElementById("lorebook-panel").dataset.monsterId === ' + JSON.stringify(id) + ' && document.querySelectorAll("#lorebook-entry [data-lore-ability]").length > 0 && document.querySelectorAll("#lorebook-entry [data-lore-sequence]").length > 0');
  }
  await page.click('#lorebook-panel button[data-monster-id="patrol"]');
  check(await page.evaluate<boolean>('document.getElementById("lorebook-entry").textContent.includes("50%")'), "Wolf lore must expose the actual coin-flip variations");
  await page.shot("wolf-lore");
  await page.click('#lorebook-panel button[data-monster-id="scout"]');
  await page.shot("head-lore");
  const reading = await page.read(); await page.key("KeyW", true);
  await page.waitFor('Number(document.body.dataset.gamePlayerZ) > ' + (Number(reading.gamePlayerZ) + .25));
  await page.key("KeyW", false);
  check(await page.evaluate<boolean>('!document.getElementById("lorebook-panel").hidden'), "Moving must leave the lorebook open");
  await page.press("Escape"); await page.waitFor('document.getElementById("lorebook-panel").hidden && document.body.dataset.gamePaused === "false"');
  await page.press("KeyL"); await page.click("#lorebook-close");
  await page.waitFor('document.getElementById("lorebook-panel").hidden');
  await moveTo(5, -11);
  await page.press("KeyF");
  await page.waitFor('!document.getElementById("inn-panel").hidden && document.getElementById("chat-log-messages").textContent.includes("Rowan")');
  await page.shot("inn");
  const atInn = await page.read();
  await page.key("KeyW", true);
  await page.waitFor(`Number(document.body.dataset.gamePlayerZ) > ${Number(atInn.gamePlayerZ) + 0.25}`);
  await page.key("KeyW", false);
  check(await page.evaluate<boolean>('!document.getElementById("inn-panel").hidden'), "Movement closed the nearby inn");
  await page.click("#inn-close");
  await page.waitFor('document.getElementById("inn-panel").hidden');
  await page.press("KeyF");
  await page.waitFor('!document.getElementById("inn-panel").hidden');
  await page.press("Escape");
  await page.waitFor('document.getElementById("inn-panel").hidden && document.body.dataset.gamePaused === "false"');
  await moveTo(3.4, -7.5, 0.6);
  await page.waitFor('document.body.dataset.adventureAudioUnlocked === "true" && Number(document.body.dataset.adventureAudioSamples) === 10');
  const musicTime = await page.evaluate<number>('document.getElementById("adventure-music").currentTime');
  await page.waitFor(`document.getElementById("adventure-music").currentTime > ${musicTime + 0.2}`);
  await page.press("KeyF");
  await page.waitFor('Boolean(document.getElementById("shop-buy-potion")?.getClientRects().length)');
  await page.waitFor('document.getElementById("shop-portrait").complete && document.getElementById("shop-portrait").naturalWidth > 0');
  await page.shot("merchant");
  await page.click('#shop-buy-potion');
  await page.waitFor('Number(document.body.dataset.gamePotions) === 1 && Number(document.body.dataset.gameSupplies) === 12');
  const shopping = await page.read();
  await page.key("KeyW", true);
  await page.waitFor(`Number(document.body.dataset.gamePlayerZ) > ${Number(shopping.gamePlayerZ) + 0.25}`);
  await page.key("KeyW", false);
  check(await page.evaluate<boolean>('!document.getElementById("shop-panel").hidden'), "Movement closed the shop");
  await page.click('#shop-close');
  await moveTo(0, -2);
  await moveTo(0, 2.1, 0.2);
  const lookout = '.enemy-nameplate[data-enemy-id="scout"]';
  const enemy = () => page.evaluate<Record<string,string>>('({...document.querySelector(' + JSON.stringify(lookout) + ').dataset})');
  for (const [slot, name] of [["auto", "Ember Beam"], ["next", "Ember Ward"]] as const) {
    const selector = lookout + ' [data-ability-slot="' + slot + '"]';
    const point = await page.evaluate<{x:number;y:number}>('(() => {const r=document.querySelector(' + JSON.stringify(selector) + ').getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height/2}})()');
    await page.call("Input.dispatchMouseEvent", {type:"mouseMoved",...point,buttons:0});
    await page.waitFor('(() => {const tip=document.querySelector(' + JSON.stringify(selector + ' [role="tooltip"]') + ');return getComputedStyle(tip).display !== "none" && tip.textContent.includes(' + JSON.stringify(name) + ')})()');
    check(await page.evaluate<boolean>('(() => {const r=document.querySelector(' + JSON.stringify(selector) + ').getBoundingClientRect();const h=document.querySelector(' + JSON.stringify(lookout+' .nameplate-health') + ').getBoundingClientRect(); return r.top > h.bottom;})()'), "Intent icon must be below health");
    await page.shot("before-combat-" + slot);
  }
  await page.call("Input.dispatchMouseEvent", {type:"mouseMoved",x:700,y:400,buttons:0});
  await page.click(lookout + ' .nameplate-target');
  await moveTo(-3, 8, 0.2);
  await page.waitFor('Number(document.querySelector(' + JSON.stringify(lookout) + ').dataset.autoAttackSequence) === 1');
  check(Number((await page.read()).gamePlayerVitality) === 99, "Stored opener beam must deal 1 targeted damage");
  check(Number((await enemy()).block) === 6, "Stored opener must raise an actual ward");
  const pair = JSON.parse((await enemy()).forecast!) as {id:string;seconds:number;status:string}[];
  check(pair.length === 2 && pair[0]!.id === "fireball" && pair[1]!.id === "ember-ward" && Math.abs(pair[0]!.seconds-pair[1]!.seconds)<.05, "First two-move forecast must announce simultaneous Fireball and Ward");
  await page.click('[data-action="bloodRage"]');
  await page.waitFor('Number(document.body.dataset.gameBloodRage) === 1 && Number(document.body.dataset.gameStamina) === 2');
  check(await page.evaluate<boolean>('!document.getElementById("player-action-bar").hidden && document.getElementById("player-action-name").textContent.includes("Blood Rage")'), "Blood Rage needs its own recovery bar");
  await page.shot("blood-rage-hotbar");
  await page.call("Input.dispatchMouseEvent", {type:"mouseMoved",x:700,y:400,buttons:0});
  await page.waitFor('(() => {const p=JSON.parse(document.querySelector(' + JSON.stringify(lookout) + ').dataset.forecast);return p[0]?.id === "ember-ward" && p[0].seconds < .45 && p[0].seconds > .1;})()');
  await page.press("Digit3");
  await page.waitFor('Number(document.body.dataset.gameBlock) === 10');
  await page.shot("head-fireball-warning");
  await page.waitFor('Number(document.querySelector(' + JSON.stringify(lookout) + ').dataset.autoAttackSequence) === 3 && Number(document.querySelector(' + JSON.stringify(lookout) + ').dataset.projectileCount) === 0',8000);
  check(Number((await page.read()).gameBlock) === 6, "One brief block must absorb fireball 3 plus beam 1");
  check(Number((await enemy()).block) === 6, "Second ward should provide 6 actual block");
  const beforeLunge=await page.read();
  await page.click('[data-action="strike"]');
  await page.waitFor('Number(document.querySelector(' + JSON.stringify(lookout) + ').dataset.health) === 67');
  check(Number((await enemy()).block) === 0, "Rage-boosted Lunge must consume enemy block before health");
  const afterLunge=await page.read();
  check(Math.hypot(Number(afterLunge.gamePlayerX)-Number(beforeLunge.gamePlayerX),Number(afterLunge.gamePlayerZ)-Number(beforeLunge.gamePlayerZ)) > 0.2, "Lunge must move toward the head");
  await page.waitFor('document.querySelector(' + JSON.stringify(lookout) + ').dataset.currentAbility === "kindle"',8000);
  await page.shot("head-kindle-opening");
  await page.press("Digit1");
  await page.waitFor('Number(document.querySelector(' + JSON.stringify(lookout) + ').dataset.health) === 56');
  await page.waitFor('Number(document.querySelector(' + JSON.stringify(lookout) + ').dataset.projectileCount) === 2',16000);
  await Bun.sleep(250);await page.shot("head-two-fireballs");
  await page.waitFor('Number(document.querySelector(' + JSON.stringify(lookout) + ').dataset.volley) === 3',16000);
  await page.waitFor('Number(document.querySelector(' + JSON.stringify(lookout) + ').dataset.projectileCount) === 3',8000);
  await Bun.sleep(250);await page.shot("head-three-fireballs");
  await page.press("Digit3");
  const deadline = performance.now() + 30000;
  while (Number((await enemy()).health) > 0 && performance.now() < deadline) {
    await page.press("Digit1"); await Bun.sleep(150);
  }
  check((await enemy()).phase === "cleared", "Ember head could not be defeated with the prototype abilities");
  await page.waitFor('Number(document.body.dataset.gameBloodRage) === 0',5000);
  const corpse = await enemy();
  await moveTo(Number(corpse.worldX), Number(corpse.worldZ), 0.5);
  await page.press("KeyF");
  await page.waitFor('!document.getElementById("loot-window").hidden && document.getElementById("loot-window").dataset.lootSource === "scout"');
  check(await page.evaluate<boolean>('(() => {const frame=document.getElementById("loot-window").getBoundingClientRect(), close=document.getElementById("loot-close").getBoundingClientRect(); return Math.abs(frame.top+3-close.top)<1 && Math.abs(frame.right-3-close.right)<1;})()'), "Loot close button is not aligned to the frame corner");
  const lootQuantity = await page.evaluate<number>('Number(document.getElementById("loot-window").dataset.lootQuantity)');
  const inspectingLoot = await page.read();
  await page.key("KeyW", true);
  await page.waitFor(`Number(document.body.dataset.gamePlayerZ) > ${Number(inspectingLoot.gamePlayerZ) + 0.25}`);
  check(await page.evaluate<boolean>('!document.getElementById("loot-window").hidden'), "Movement closed nearby loot");
  await page.press("Escape");
  await page.waitFor('document.getElementById("loot-window").hidden && document.body.dataset.gamePaused === "false"');
  const closedLoot = await page.read();
  await page.waitFor(`Number(document.body.dataset.gamePlayerZ) > ${Number(closedLoot.gamePlayerZ) + 0.25}`);
  await page.key("KeyW", false);
  await moveTo(Number(inspectingLoot.gamePlayerX), Number(inspectingLoot.gamePlayerZ), 0.15);
  await page.press("KeyF");
  await page.waitFor('!document.getElementById("loot-window").hidden');
  await page.click("#loot-close");
  await page.waitFor('document.getElementById("loot-window").hidden');
  await page.press("KeyF");
  await page.waitFor('!document.getElementById("loot-window").hidden');
  await page.shot("corpse-loot");
  await page.reload();
  await page.waitFor('document.body.dataset.entryRoute === "world" && document.body.dataset.rigState === "ready"');
  await page.press("KeyF");
  await page.waitFor('!document.getElementById("loot-window").hidden && document.getElementById("loot-window").dataset.lootSource === "scout"');
  await page.click("#loot-item");
  await page.waitFor(`Number(document.body.dataset.gameCarriedSalvage) === ${lootQuantity} && document.getElementById("loot-window").hidden`);
  const looted = await page.read();
  await page.press("KeyB");
  await page.waitFor(`Number(document.querySelector('[data-bag-item="carriedSalvage"]')?.dataset.quantity) === ${lootQuantity}`);
  await page.click('[data-bag-item="carriedSalvage"]');
  await page.shot("backpack-loot");
  await page.press("Escape");
  check(Number(looted.gameSupplies) === 12, "Loot was banked before extraction");
  await page.press("KeyF");
  await page.waitFor('document.getElementById("loot-window").hidden');
  check(Number((await page.read()).gameCarriedSalvage) === lootQuantity, "Corpse loot was duplicated");
  await moveTo(-2, 12);
  await page.waitFor('document.body.dataset.gamePhase === "expedition"');
  await page.press("KeyG");
  await page.waitFor('Number(document.body.dataset.gameCargo) === 3');
  const gathered = await page.read();
  check(Number(gathered.gamePlayerVitality) < 100, "Thorn gathering cost was not applied");
  await page.press("KeyB");
  await page.waitFor('!document.getElementById("bag-panel").hidden');
  await page.click('[data-bag-item="potions"]');
  await page.waitFor('!document.getElementById("bag-details").hidden');
  await page.shot("potion-tooltip");
  const beforePotion = Number((await page.read()).gamePlayerVitality);
  await page.click('#bag-use-potion');
  await page.waitFor('Number(document.body.dataset.gamePotions) === 0 && Number(document.body.dataset.gamePlayerVitality) === ' + Math.min(100,beforePotion+30));
  await page.press("KeyB");
  await page.waitFor('document.getElementById("bag-details").hidden');
  await page.waitFor('Number(document.body.dataset.gameActionCooldown) === 0');
  await moveTo(0, 16);
  await moveTo(4.2, 17.65, 0.25);
  const nest = '.enemy-nameplate[data-enemy-id="nest"]';
  await page.evaluate(`document.querySelector('${nest}')?.click()`);
  await page.waitFor(`document.querySelector('${nest}')?.dataset.disposition === "neutral" && document.querySelector('${nest}')?.dataset.aggro === "false"`);
  await page.waitFor('document.getElementById("target-frame").dataset.targetId === "nest" && document.getElementById("target-frame").dataset.hostile === "false" && document.getElementById("target-of-target-frame").hidden');
  await page.shot("neutral-nest");
  await page.press("Digit1");
  await page.waitFor(`document.querySelector('${nest}')?.dataset.aggro === "true"`);
  await page.waitFor('document.getElementById("target-frame").dataset.hostile === "true" && !document.getElementById("target-of-target-frame").hidden && document.getElementById("target-of-target-frame").dataset.targetId === document.getElementById("player-frame").dataset.targetId');
  await page.click('#chat-log-tab-combat');
  await page.waitFor('document.getElementById("chat-log").dataset.logChannel === "combat" && document.getElementById("chat-log-messages").textContent.includes("You lunge at Thorn nest")');
  await page.waitFor('Number(document.body.dataset.gameActionCooldown) === 0');
  await page.waitFor(`document.querySelector('${nest}')?.dataset.phase === "preparation" && Number(document.querySelector('${nest}')?.dataset.remaining) > 0.7 && Number(document.querySelector('${nest}')?.dataset.remaining) < 1.4`);
  const beforeBrace = await page.read();
  const predictedDamage = await page.evaluate<number>(`Number(document.querySelector('${nest}')?.dataset.damage)`);
  const firstSequence = await page.evaluate<number>(`Number(document.querySelector('${nest}')?.dataset.actionSequence)`);
  await page.press("KeyE");
  await page.waitFor('Number(document.body.dataset.gameGuardSeconds) > 0');
  await page.shot("forecast");
  await page.waitFor(`Number(document.querySelector('${nest}')?.dataset.actionSequence) > ${firstSequence}`, 8_000);
  const braced = await page.read();
  check(Number(beforeBrace.gamePlayerVitality) - Number(braced.gamePlayerVitality) === Math.max(0, predictedDamage - 10), "Block did not absorb 10 of the forecast hit");
  await page.shot("braced-hit");
  await page.waitFor('document.getElementById("chat-log-messages").textContent.includes("blocked")');
  await page.waitFor(`document.querySelector('${nest}')?.dataset.strikeOpening === "true"`);
  await page.shot("strike-opening");
  await page.waitFor(`document.querySelector('${nest}')?.dataset.phase === "preparation" && document.querySelector('${nest}')?.dataset.strikeOpening === "false"`);
  await page.waitFor(`document.querySelector('${nest}')?.dataset.phase === "preparation" && Number(document.querySelector('${nest}')?.dataset.remaining) > 2.2`);
  const secondSequence = await page.evaluate<number>(`Number(document.querySelector('${nest}')?.dataset.actionSequence)`);
  await moveTo(0, 16);
  await page.waitFor(`Number(document.querySelector('${nest}')?.dataset.actionSequence) > ${secondSequence}`, 8_000);
  const avoided = await page.read();
  check(Number(avoided.gamePlayerVitality) === Number(braced.gamePlayerVitality), "Stepping outside the warning failed to avoid damage");
  await page.shot("avoided-hit");
  await page.waitFor('document.getElementById("chat-log-messages").textContent.includes("misses you")');
  await moveTo(0, 5);
  await moveTo(0, -2);
  await page.waitFor('document.body.dataset.gamePhase === "town" && Number(document.body.dataset.gameCargo) === 0');
  const returned = await page.read();
  check(Number(returned.gameSupplies) === 15 + lootQuantity && Number(returned.gameCarriedSalvage) === 0, "Living return did not bank gathered cores and corpse salvage");
  await page.shot("returned");
  await moveTo(0, -8);
  await moveTo(5, -11);
  await page.press("KeyF");
  await page.waitFor('!document.getElementById("inn-panel").hidden');
  await page.click("#inn-rest");
  await page.waitFor('Number(document.body.dataset.gamePlayerVitality) === 100 && document.getElementById("player-frame").dataset.health === "100"');
  check(Number((await page.read()).gameSupplies) === Number(returned.gameSupplies), "Inn charged for free rest");
  await page.click('#chat-log-tab-chat');
  await page.waitFor('document.getElementById("chat-log-messages").textContent.includes("rest")');
  await page.shot("rested");
  await page.click("#inn-close");
  await page.reload();
  await page.waitFor('["roster", "world"].includes(document.body.dataset.entryRoute)');
  await page.evaluate('if(document.body.dataset.entryRoute === "roster") document.getElementById("entry-enter-world").click()');
  await page.waitFor(`document.body.dataset.entryRoute === "world" && Number(document.body.dataset.gameSupplies) === ${15 + lootQuantity}`);
  check(page.errors.length === 0, "Browser exceptions occurred");
  await Bun.write(`${page.output}/result.json`, JSON.stringify({ gathered, lootQuantity, looted, beforeBrace, predictedDamage, braced, avoided, returned, reopened: await page.read(), errors: page.errors }, null, 2));
  console.log(`PASS: Lorebook L and movement, icon hotbar, Blood Rage and stamina, stored head opener, paired forecasts, block overlap, enemy ward, Kindle and escalating volleys; inn, merchant, bag, loot/reload, neutral/aggro, log, nest defense/dodge, extraction. Evidence: ${page.output}`);
} finally { await hold([]).catch(() => {}); await page.close(); }
