import { COMBAT_RULES } from "../../src/game/adventure.js";
import { check, openBrowser } from "./session.js";

const page = await openBrowser("expedition");
const held = new Set<string>();
async function hold(desired: readonly string[]) {
  for (const code of held) if (!desired.includes(code)) { await page.key(code, false); held.delete(code); }
  for (const code of desired) if (!held.has(code)) { await page.key(code, true); held.add(code); }
}
async function moveTo(x: number, z: number, tolerance = 0.5) {
  const deadline = performance.now() + 18_000;
  while (performance.now() < deadline) {
    const state = await page.read();
    check(state.gamePhase !== "lost", "Character fell while walking the route");
    const dx = x - Number(state.gamePlayerX), dz = z - Number(state.gamePlayerZ);
    if (Math.hypot(dx, dz) <= tolerance) { await hold([]); return; }
    const next: string[] = [];
    // Initial camera faces north (+z), putting world +x to the player's left.
    if (Math.abs(dx) > tolerance / 2) next.push(dx > 0 ? "KeyA" : "KeyD");
    if (Math.abs(dz) > tolerance / 2) next.push(dz > 0 ? "KeyW" : "KeyS");
    await hold(next);
    await Bun.sleep(100);
  }
  throw new Error(`Could not reach ${x},${z}: ${JSON.stringify(await page.read())}`);
}
try {
  await page.enter();
  await page.waitFor('[...document.querySelectorAll("#player-frame img, #target-frame img")].every(image => image.complete && image.naturalWidth > 0)');
  await page.press("KeyJ");
  await page.waitFor('!document.getElementById("lorebook-panel").hidden');
  for (const id of ["scout", "patrol", "nest", "warder", "ritual-guardian"]) {
    await page.click('#lorebook-panel button[data-monster-id="' + id + '"]');
    await page.waitFor('document.getElementById("lorebook-panel").dataset.monsterId === ' + JSON.stringify(id) + ' && document.querySelectorAll("#lorebook-entry [data-lore-ability]").length > 0 && document.querySelectorAll("#lorebook-entry [data-lore-sequence]").length > 0');
  }
  await page.click('#lorebook-panel button[data-monster-id="patrol"]');
  check(await page.evaluate<boolean>('document.querySelectorAll("#lorebook-entry [data-lore-ability]").length === 1 && document.getElementById("lorebook-entry").textContent.includes("Maul")'), "Hound lore must describe its sole attack, Maul");
  await page.shot("wolf-lore");
  await page.click('#lorebook-panel button[data-monster-id="scout"]');
  await page.shot("head-lore");
  const reading = await page.read(); await page.key("KeyW", true);
  await page.waitFor('Number(document.body.dataset.gamePlayerZ) > ' + (Number(reading.gamePlayerZ) + .25));
  await page.key("KeyW", false);
  check(await page.evaluate<boolean>('!document.getElementById("lorebook-panel").hidden'), "Moving must leave the lorebook open");
  await page.press("Escape"); await page.waitFor('document.getElementById("lorebook-panel").hidden && document.body.dataset.gamePaused === "false"');
  await page.press("KeyJ"); await page.click("#lorebook-close");
  await page.waitFor('document.getElementById("lorebook-panel").hidden');
  await moveTo(5, -11);
  await page.press("KeyF");
  await page.waitFor('!document.getElementById("inn-panel").hidden && document.getElementById("chat-log-messages").textContent.includes("Rowan")');
  await page.shot("inn");
  const atInn = await page.read();
  await page.key("KeyW", true);
  await page.waitFor(`Number(document.body.dataset.gamePlayerZ) > ${Number(atInn.gamePlayerZ) + 0.25}`);
  await page.key("KeyW", false);
  check(await page.evaluate<boolean>('!document.getElementById("inn-panel").hidden'), "Movement closed the nearby inn");
  await page.click("#inn-close");
  await page.waitFor('document.getElementById("inn-panel").hidden');
  await page.press("KeyF");
  await page.waitFor('!document.getElementById("inn-panel").hidden');
  await page.press("Escape");
  await page.waitFor('document.getElementById("inn-panel").hidden && document.body.dataset.gamePaused === "false"');
  await moveTo(3.4, -7.5, 0.6);
  await page.waitFor('document.body.dataset.adventureAudioUnlocked === "true" && Number(document.body.dataset.adventureAudioSamples) === 10');
  const musicTime = await page.evaluate<number>('document.getElementById("adventure-music").currentTime');
  await page.waitFor(`document.getElementById("adventure-music").currentTime > ${musicTime + 0.2}`);
  await page.press("KeyF");
  await page.waitFor('Boolean(document.getElementById("shop-buy-potion")?.getClientRects().length)');
  await page.waitFor('document.getElementById("shop-portrait").complete && document.getElementById("shop-portrait").naturalWidth > 0');
  await page.shot("merchant");
  await page.click('#shop-buy-potion');
  await page.waitFor('Number(document.body.dataset.gamePotions) === 1 && Number(document.body.dataset.gameSupplies) === 12');
  const shopping = await page.read();
  await page.key("KeyW", true);
  await page.waitFor(`Number(document.body.dataset.gamePlayerZ) > ${Number(shopping.gamePlayerZ) + 0.25}`);
  await page.key("KeyW", false);
  check(await page.evaluate<boolean>('!document.getElementById("shop-panel").hidden'), "Movement closed the shop");
  await page.click('#shop-close');
  await moveTo(0, -2);
  await moveTo(0, 2.1, 0.2);
  const lookout = '.enemy-nameplate[data-enemy-id="scout"]';
  const enemy = () => page.evaluate<Record<string,string>>('({...document.querySelector(' + JSON.stringify(lookout) + ').dataset})');
  for (const [slot, name] of [["next", "Ember Beam"]] as const) {
    const selector = lookout + ' [data-ability-slot="' + slot + '"]';
    const point = await page.evaluate<{x:number;y:number}>('(() => {const r=document.querySelector(' + JSON.stringify(selector) + ').getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height/2}})()');
    await page.call("Input.dispatchMouseEvent", {type:"mouseMoved",...point,buttons:0});
    await page.waitFor('(() => {const tip=document.querySelector(' + JSON.stringify(selector + ' [role="tooltip"]') + ');return getComputedStyle(tip).display !== "none" && tip.textContent.includes(' + JSON.stringify(name) + ')})()');
    check(await page.evaluate<boolean>('(() => {const r=document.querySelector(' + JSON.stringify(selector) + ').getBoundingClientRect();const h=document.querySelector(' + JSON.stringify(lookout+' .nameplate-health') + ').getBoundingClientRect(); return r.top > h.bottom;})()'), "Intent icon must be below health");
    await page.shot("before-combat-" + slot);
  }
  await page.call("Input.dispatchMouseEvent", {type:"mouseMoved",x:700,y:400,buttons:0});
  await page.click(lookout + ' .nameplate-target');
  const plan = () => page.evaluate<{ id:number; action:string; offsetSeconds:number; status:string }[]>('JSON.parse(document.getElementById("combat-plan").dataset.queued)');
  await page.press("KeyE");
  await page.waitFor('Number(document.body.dataset.gameReservedStamina) === 2');
  check(Number((await page.read()).gameStamina) === 5 && Number((await page.read()).gameBlock) === 0, "Planning must reserve stamina without spending or guarding early");
  await page.shot("prequeued-opening-block");
  await hold(["KeyW"]);
  await page.waitFor('document.body.dataset.gameCombatPhase === "active"');
  await hold([]);
  check(Number((await page.read()).gamePlayerVitality) === 100, "Prequeued Block failed to protect from the opening Beam");
  check(Number((await page.read()).gameBlock) === 9, "Opening Beam must consume one point of the prequeued Block");
  await page.waitFor('document.body.dataset.gameCombatPhase === "preparation"');
  check(Number((await page.read()).gameStamina) === 5, "Preparation must refill five stamina");
  await page.press("KeyQ"); await page.press("KeyE");
  await page.waitFor('document.querySelectorAll(".combat-plan-move").length === 2');
  let moves = await plan();
  check(moves[0]?.offsetSeconds === 0 && moves[1]?.offsetSeconds === 1, "QE must queue at zero and one seconds");
  await page.press("Digit3");
  await page.waitFor('JSON.parse(document.getElementById("combat-plan").dataset.queued)[1]?.offsetSeconds === 2');
  await page.press('Digit2');
  await page.waitFor('JSON.parse(document.getElementById("combat-plan").dataset.queued)[1]?.offsetSeconds === 1');
  const upcomingCycle = Number((await page.read()).gameCombatCycle) + 1;
  const fireballBeat = await page.evaluate<number>('Number(document.querySelector(".combat-plan-enemy-move[data-ability-id=fireball]")?.dataset.offset)');
  await page.waitFor('document.body.dataset.gameCombatPhase === "active" && Number(document.body.dataset.gameCombatCycle) === ' + upcomingCycle);
  await page.press("Digit3");
  await page.waitFor('JSON.parse(document.getElementById("combat-plan").dataset.queued)[1]?.offsetSeconds === 2');
  moves = await plan();
  check(moves[0]?.status === "executed" && moves[1]?.status === "pending", "Last-second retiming must leave the executed Lunge locked and Block pending");
  await page.shot("live-queue-adjustment");
  await page.waitFor('JSON.parse(document.getElementById("combat-plan").dataset.queued)[1]?.status === "executed"');
  check(Number((await page.read()).gameBlock) === (fireballBeat === 2 ? COMBAT_RULES.brace.block-COMBAT_RULES.head.fireballDamage : COMBAT_RULES.brace.block), "Retimed Block must absorb only the fireball when it shares slot 3");
  await page.waitFor('document.body.dataset.gameCombatPhase === "preparation"');
  for (const code of ["KeyQ", "KeyN", "KeyV"]) await page.press(code);
  await page.waitFor('document.querySelectorAll(".combat-plan-move").length === 3');
  moves = await plan();
  check(moves.map(move=>move.offsetSeconds).join(',') === '0,1,2', "Paid moves and free fillers must each occupy one beat");
  const jab = moves.find(move=>move.action === 'jab')!;
  await page.click('.combat-plan-move[data-queue-id="' + jab.id + '"]');
  await page.call('Input.dispatchKeyEvent', {type:'keyDown',code:'Digit2',key:'@',windowsVirtualKeyCode:50,modifiers:8});
  await page.call('Input.dispatchKeyEvent', {type:'keyUp',code:'Digit2',key:'@',windowsVirtualKeyCode:50,modifiers:8});
  await page.waitFor('JSON.parse(document.getElementById("combat-plan").dataset.queued).find(move=>move.action === "jab")?.offsetSeconds === 1');
  check((await plan()).find(move=>move.action === 'guard')?.offsetSeconds === 2, "Swapping must move the displaced ability into the old beat");
  const dropPoint = await page.evaluate<{x:number;y:number}>('(() => {const r=document.querySelectorAll(".combat-plan-player")[2].getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height/2}})()');
  const dragData = { items: [{mimeType:'application/x-greywrought-move',data:String(jab.id)}], dragOperationsMask: 16 };
  for (const type of ['dragEnter','dragOver','drop']) await page.call('Input.dispatchDragEvent', {type,...dropPoint,data:dragData});
  await page.waitFor('JSON.parse(document.getElementById("combat-plan").dataset.queued).find(move=>move.action === "jab")?.offsetSeconds === 2');
  check((await plan()).find(move=>move.action === 'guard')?.offsetSeconds === 1, "Dropping onto an occupied beat must swap both pending moves");
  await page.shot("three-beat-plan");
  await page.reload();
  await page.waitFor('document.body.dataset.entryRoute === "world" && document.body.dataset.rigState === "ready"');
  check((await plan()).some(move=>move.action === 'jab' && move.offsetSeconds === 2), "Reload lost the edited plan");
  await page.waitFor('document.body.dataset.gameCombatPhase === "preparation" && Number(document.getElementById("combat-plan").dataset.remaining) > 3',12000);
  await page.click('.combat-plan-clear');
  for (let i=0;i<3;i++) await page.press('KeyQ');
  await page.waitFor('document.querySelectorAll(".combat-plan-move").length === 3 && Number(document.body.dataset.gameReservedStamina) === 3');
  check(Number((await page.read()).gameReservedStamina) === 3, "Three one-stamina moves fit the action window");
  await page.press('KeyV');
  check((await plan()).length === 3, "A free filler must not create a fourth move");
  await page.shot("full-three-move-plan");
  const deadline = performance.now() + 70000;
  while (Number((await enemy()).health) > 0 && performance.now() < deadline) {
    await page.press("KeyQ"); await Bun.sleep(160);
  }
  check((await enemy()).phase === "cleared", "Ember head could not be defeated with queued Lunge sequences");
  const corpse = await enemy();
  await moveTo(Number(corpse.worldX), Number(corpse.worldZ), 0.5);
  await page.press("KeyF");
  await page.waitFor('!document.getElementById("loot-window").hidden && document.getElementById("loot-window").dataset.lootSource === "scout"');
  check(await page.evaluate<boolean>('(() => {const frame=document.getElementById("loot-window").getBoundingClientRect(), close=document.getElementById("loot-close").getBoundingClientRect(); return Math.abs(frame.top+3-close.top)<1 && Math.abs(frame.right-3-close.right)<1;})()'), "Loot close button is not aligned to the frame corner");
  const lootQuantity = await page.evaluate<number>('Number(document.getElementById("loot-window").dataset.lootQuantity)');
  const inspectingLoot = await page.read();
  await page.key("KeyW", true);
  await page.waitFor(`Number(document.body.dataset.gamePlayerZ) > ${Number(inspectingLoot.gamePlayerZ) + 0.25}`);
  check(await page.evaluate<boolean>('!document.getElementById("loot-window").hidden'), "Movement closed nearby loot");
  await page.press("Escape");
  await page.waitFor('document.getElementById("loot-window").hidden && document.body.dataset.gamePaused === "false"');
  const closedLoot = await page.read();
  await page.waitFor(`Number(document.body.dataset.gamePlayerZ) > ${Number(closedLoot.gamePlayerZ) + 0.25}`);
  await page.key("KeyW", false);
  await moveTo(Number(inspectingLoot.gamePlayerX), Number(inspectingLoot.gamePlayerZ), 0.15);
  await page.press("KeyF");
  await page.waitFor('!document.getElementById("loot-window").hidden');
  await page.click("#loot-close");
  await page.waitFor('document.getElementById("loot-window").hidden');
  await page.press("KeyF");
  await page.waitFor('!document.getElementById("loot-window").hidden');
  await page.shot("corpse-loot");
  await page.reload();
  await page.waitFor('document.body.dataset.entryRoute === "world" && document.body.dataset.rigState === "ready"');
  await page.press("KeyF");
  await page.waitFor('!document.getElementById("loot-window").hidden && document.getElementById("loot-window").dataset.lootSource === "scout"');
  await page.click("#loot-item");
  await page.waitFor(`Number(document.body.dataset.gameCarriedSalvage) === ${lootQuantity} && document.getElementById("loot-window").hidden`);
  const looted = await page.read();
  await page.press("KeyB");
  await page.waitFor(`Number(document.querySelector('[data-bag-item="carriedSalvage"]')?.dataset.quantity) === ${lootQuantity}`);
  await page.click('[data-bag-item="carriedSalvage"]');
  await page.shot("backpack-loot");
  await page.press("Escape");
  check(Number(looted.gameSupplies) === 12, "Loot was banked before extraction");
  await page.press("KeyF");
  await page.waitFor('document.getElementById("loot-window").hidden');
  check(Number((await page.read()).gameCarriedSalvage) === lootQuantity, "Corpse loot was duplicated");
  await moveTo(-2, 12);
  await page.waitFor('document.body.dataset.gamePhase === "expedition"');
  await page.press("KeyG");
  await page.waitFor('Number(document.body.dataset.gameCargo) === 3');
  const gathered = await page.read();
  check(Number(gathered.gamePlayerVitality) < 100, "Thorn gathering cost was not applied");
  await page.press("KeyB");
  await page.waitFor('!document.getElementById("bag-panel").hidden');
  await page.click('[data-bag-item="potions"]');
  await page.waitFor('!document.getElementById("bag-details").hidden');
  await page.shot("potion-tooltip");
  const beforePotion = Number((await page.read()).gamePlayerVitality);
  await page.click('#bag-use-potion');
  await page.waitFor('Number(document.body.dataset.gamePotions) === 0 && Number(document.body.dataset.gamePlayerVitality) === ' + Math.min(100,beforePotion+30));
  await page.press("KeyB");
  await page.waitFor('document.getElementById("bag-details").hidden');
  await page.waitFor('Number(document.body.dataset.gameActionCooldown) === 0');
  await moveTo(0, 16);
  await moveTo(4.2, 17.65, 0.25);
  const nest = '.enemy-nameplate[data-enemy-id="nest"]';
  await page.evaluate(`document.querySelector('${nest}')?.click()`);
  await page.waitFor(`document.querySelector('${nest}')?.dataset.disposition === "neutral" && document.querySelector('${nest}')?.dataset.aggro === "false"`);
  await page.waitFor('document.getElementById("target-frame").dataset.targetId === "nest" && document.getElementById("target-frame").dataset.hostile === "false" && document.getElementById("target-of-target-frame").hidden');
  await page.shot("neutral-nest");
  await page.press("KeyQ");
  await page.waitFor(`document.querySelector('${nest}')?.dataset.aggro === "true"`);
  await page.waitFor('document.getElementById("target-frame").dataset.hostile === "true" && !document.getElementById("target-of-target-frame").hidden && document.getElementById("target-of-target-frame").dataset.targetId === document.getElementById("player-frame").dataset.targetId');
  await page.click('#chat-log-tab-combat');
  await page.waitFor('document.getElementById("chat-log").dataset.logChannel === "combat" && document.getElementById("chat-log-messages").textContent.includes("You lunge at Thorn nest")');
  await page.waitFor('Number(document.body.dataset.gameActionCooldown) === 0');
  await page.waitFor('document.body.dataset.gameCombatPhase === "preparation" && Number(document.getElementById("combat-plan").dataset.remaining) > 3',12000);
  const beforeBrace = await page.read();
  const predictedDamage = await page.evaluate<number>(`Number(document.querySelector('${nest}')?.dataset.damage)`);
  const nestBeat = await page.evaluate<number>('Math.floor(Number(document.querySelector(".combat-plan-enemy-move[data-ability-id=nest]")?.dataset.offset))');
  const firstSequence = await page.evaluate<number>(`Number(document.querySelector('${nest}')?.dataset.actionSequence)`);
  await page.press("KeyE");
  if (nestBeat > 0) await page.press("Digit" + nestBeat);
  await page.waitFor('Number(document.body.dataset.gameGuardSeconds) > 0',12000);
  await page.shot("forecast");
  await page.waitFor(`Number(document.querySelector('${nest}')?.dataset.actionSequence) > ${firstSequence}`, 8_000);
  const braced = await page.read();
  check(Number(beforeBrace.gamePlayerVitality) - Number(braced.gamePlayerVitality) === Math.max(0, predictedDamage - COMBAT_RULES.brace.block), "Block did not absorb its advertised capacity");
  await page.shot("braced-hit");
  await page.waitFor('document.getElementById("chat-log-messages").textContent.includes("blocked")');
  await page.waitFor(`document.querySelector('${nest}')?.dataset.strikeOpening === "true"`);
  await page.shot("strike-opening");
  await page.waitFor('document.body.dataset.gameCombatPhase === "preparation"',12000);
  await page.waitFor('document.body.dataset.gameCombatPhase === "preparation" && Number(document.getElementById("combat-plan").dataset.remaining) > 3',12000);
  const secondSequence = await page.evaluate<number>(`Number(document.querySelector('${nest}')?.dataset.actionSequence)`);
  await moveTo(0, 16);
  await page.waitFor(`Number(document.querySelector('${nest}')?.dataset.actionSequence) > ${secondSequence}`, 8_000);
  const avoided = await page.read();
  check(Number(avoided.gamePlayerVitality) === Number(braced.gamePlayerVitality), "Stepping outside the warning failed to avoid damage");
  await page.shot("avoided-hit");
  await page.waitFor('document.getElementById("chat-log-messages").textContent.includes("misses you")');
  await moveTo(0, 5);
  await moveTo(0, -2);
  await page.waitFor('document.body.dataset.gamePhase === "town" && Number(document.body.dataset.gameCargo) === 0');
  const returned = await page.read();
  check(Number(returned.gameSupplies) === 15 + lootQuantity && Number(returned.gameCarriedSalvage) === 0, "Living return did not bank gathered cores and corpse salvage");
  await page.shot("returned");
  await moveTo(0, -8);
  await moveTo(5, -11);
  await page.press("KeyF");
  await page.waitFor('!document.getElementById("inn-panel").hidden');
  await page.click("#inn-rest");
  await page.waitFor('Number(document.body.dataset.gamePlayerVitality) === 100 && document.getElementById("player-frame").dataset.health === "100"');
  check(Number((await page.read()).gameSupplies) === Number(returned.gameSupplies), "Inn charged for free rest");
  await page.click('#chat-log-tab-chat');
  await page.waitFor('document.getElementById("chat-log-messages").textContent.includes("rest")');
  await page.shot("rested");
  await page.click("#inn-close");
  await page.reload();
  await page.waitFor('["roster", "world"].includes(document.body.dataset.entryRoute)');
  await page.evaluate('if(document.body.dataset.entryRoute === "roster") document.getElementById("entry-enter-world").click()');
  await page.waitFor(`document.body.dataset.entryRoute === "world" && Number(document.body.dataset.gameSupplies) === ${15 + lootQuantity}`);
  check(page.errors.length === 0, "Browser exceptions occurred");
  await Bun.write(`${page.output}/result.json`, JSON.stringify({ gathered, lootQuantity, looted, beforeBrace, predictedDamage, braced, avoided, returned, reopened: await page.read(), errors: page.errors }, null, 2));
  console.log(`PASS: Lorebook J and movement, five stamina, prequeued opening defense, QE/QE3 and live retiming, free fillers, keyboard swaps, queue/reload and three-move cap; inn, merchant, bag, loot/reload, neutral/aggro, log, nest defense/dodge, extraction. Evidence: ${page.output}`);
} finally { await hold([]).catch(() => {}); await page.close(); }
