import { createSharedAdventure } from '../../src/game/adventure.js';
import { terrainHeight } from '../../src/game/cave-layout.js';
import { createWorldService, type WorldSocketData } from '../../src/server/world-service.js';
import { openBrowser, check } from './session.js';
const url='http://127.0.0.1:4317/'; Bun.env.GREYWROUGHT_GAME_URL=url; Bun.env.GREYWROUGHT_DEBUG_PORT='9517'; Bun.env.GREYWROUGHT_VULKAN='1';
const character={id:'ironback-chest-fixture',name:'Cache Hunter',archetype:'warrior' as const,createdAtMillis:Date.now()}; const token='ironback-chest-fixture-token-000000000000';
const seed=createSharedAdventure();seed.join(character.id,character.name,character.archetype); const saved=JSON.parse(seed.save()); const player=saved.characters[0].state;
Object.assign(player,{phase:'expedition',position:{x:75,y:terrainHeight(75,-52),z:-52},potions:0,coins:0}); const crab=saved.world.threats.find((t:{id:string})=>t.id==='cave-crab'); Object.assign(crab,{health:0,phase:'cleared',lootClaimed:true,respawnAt:null});
const savePath=`${process.cwd()}/build/browser/ironback-chest-${process.pid}.json`; await Bun.write(savePath,JSON.stringify({version:1,accounts:[{character,tokenHash:new Bun.CryptoHasher('sha256').update(token).digest('hex')}],world:JSON.stringify(saved),chat:[],nextChatId:1}));
const service=await createWorldService({savePath,allowedOrigins:[url.slice(0,-1)]}); const server=Bun.serve<WorldSocketData>({hostname:'127.0.0.1',port:4318,fetch:(r,h)=>service.fetch(r,h),websocket:service.websocket}); const dev=Bun.spawn(['bun','scripts/dev-server.ts'],{env:{...Bun.env,GREYWROUGHT_PORT:'4317'},stdout:Bun.file('build/browser/ironback-chest-dev.log'),stderr:Bun.file('build/browser/ironback-chest-dev-errors.log')});
for(let n=0;n<100;n++){try{if((await fetch(url)).ok)break;}catch{}await Bun.sleep(100);} const page=await openBrowser('ironback-chest');
try { await page.call('Page.addScriptToEvaluateOnNewDocument',{source:`localStorage.setItem('greywrought/local-profile-v1',${JSON.stringify(JSON.stringify({version:1,displayName:'Cache Test',characters:[character],selectedCharacterId:character.id,savedAtMillis:Date.now()}))});localStorage.setItem('greywrought/world-token',${JSON.stringify(token)});const Native=WebSocket;window.WebSocket=class extends Native{constructor(url,...args){super(String(url).includes('/world')?'ws://127.0.0.1:4318/world':url,...args);this.addEventListener('message',e=>{const d=JSON.parse(e.data);if(d.type==='state')window.caveState=d.snapshot;});}};`});
  await page.reload(); await page.waitFor('document.body.dataset.entryRoute==="roster"'); await page.click('#entry-enter-world'); await page.waitFor('document.body.dataset.environmentState==="ready"');
  await page.key('KeyA',true); try { await page.waitFor('window.caveState.player.position.x>=77',10000); } finally { await page.key('KeyA',false); }
  await page.press('KeyF'); await page.waitFor('window.caveState.lootOpenId==="ironback-chest"'); check(await page.evaluate('document.getElementById("loot-source-name").textContent.includes("Ironback")'),'Chest loot window names the Ironback cache'); await page.click('#loot-item'); await page.waitFor('window.caveState.coins===18 && window.caveState.potions===2'); await page.shot('ironback-chest-open');
  await page.reload(); await page.waitFor('document.body.dataset.entryRoute==="roster"'); await page.click('#entry-enter-world'); await page.waitFor('document.body.dataset.environmentState==="ready"'); await page.waitFor('window.caveState.coins===18 && window.caveState.potions===2'); check(await page.evaluate('!window.caveState.loot.find(item=>item.sourceId==="ironback-chest").available'),'Reload preserves claimed chest'); check(page.errors.length===0,'No browser exceptions'); console.log('PASS Ironback cache approach, interaction, rewards and reload persistence',page.output);
} catch(error){await page.shot('failure');throw error;} finally {await page.close();await service.close();server.stop(true);dev.kill();await dev.exited;}
