import { createSharedAdventure } from '../../src/game/adventure.js';
import { createWorldService, type WorldSocketData } from '../../src/server/world-service.js';
import { check, openBrowser } from './session.js';

const url = 'http://127.0.0.1:4361/';
Object.assign(Bun.env, { GREYWROUGHT_GAME_URL: url, GREYWROUGHT_DEBUG_PORT: '9561', GREYWROUGHT_VULKAN: '1' });
const viewer = { id:'selection-viewer',name:'Target Explorer',archetype:'warrior' as const,createdAtMillis:1 };
const companion = { id:'selection-companion',name:'Mira',archetype:'mage' as const,createdAtMillis:2 };
const viewerToken='selection-viewer-token-0000000000000', companionToken='selection-companion-token-0000000000';
const seed=createSharedAdventure();seed.join(viewer.id,viewer.name,viewer.archetype);seed.join(companion.id,companion.name,companion.archetype);
const saved=JSON.parse(seed.save());
Object.assign(saved.characters[0].state,{phase:'town',position:{x:-1,y:0,z:-10}});
Object.assign(saved.characters[1].state,{phase:'town',position:{x:4,y:0,z:-10},health:70,potions:1});
const savePath=`${process.cwd()}/build/browser/player-selection-${process.pid}.json`;
await Bun.write(savePath,JSON.stringify({version:1,accounts:[{character:viewer,tokenHash:new Bun.CryptoHasher('sha256').update(viewerToken).digest('hex')},{character:companion,tokenHash:new Bun.CryptoHasher('sha256').update(companionToken).digest('hex')}],world:JSON.stringify(saved),chat:[],nextChatId:1}));
const service=await createWorldService({savePath,allowedOrigins:[url.slice(0,-1)]});
const server=Bun.serve<WorldSocketData>({hostname:'127.0.0.1',port:4362,fetch:(request,host)=>service.fetch(request,host),websocket:service.websocket});
const frontend=Bun.spawn([process.execPath,'scripts/dev-server.ts'],{env:{...Bun.env,GREYWROUGHT_PORT:'4361',GREYWROUGHT_LOCAL_WORLD:'0'},stdout:Bun.file('build/browser/player-selection-frontend.log'),stderr:Bun.file('build/browser/player-selection-frontend-errors.log')});
const bot=new WebSocket('ws://127.0.0.1:4362/world');
let botSequence=0;
await new Promise<void>((resolve,reject)=>{bot.onopen=()=>bot.send(JSON.stringify({type:'join',token:companionToken,character:companion}));bot.onmessage=e=>{if(JSON.parse(String(e.data)).type==='state')resolve();};bot.onerror=()=>reject(new Error('Companion failed to connect'));});
let page:Awaited<ReturnType<typeof openBrowser>>|undefined;
try {
  for(let i=0;i<100;i++){try{if((await fetch(url)).ok)break;}catch{}await Bun.sleep(100);}
  page=await openBrowser('player-selection',{beforeNavigate:async call=>{
    await call('Network.enable');await call('Network.setBlockedURLs',{urls:[url+'__dev/events']});
    await call('Page.addScriptToEvaluateOnNewDocument',{source:`localStorage.setItem('greywrought/local-profile-v1',${JSON.stringify(JSON.stringify({version:1,displayName:'Selection',characters:[viewer],selectedCharacterId:viewer.id,savedAtMillis:Date.now()}))});localStorage.setItem('greywrought/world-token',${JSON.stringify(viewerToken)});window.selectionCommands=[];const Native=WebSocket;window.WebSocket=class extends Native{constructor(url,...args){super(String(url).includes('/world')?'ws://127.0.0.1:4362/world':url,...args);this.addEventListener('message',e=>{const d=window.decodeWorldMessage(e);if(d.type==='state')window.selectionState=d;});}send(data){const d=JSON.parse(data);if(d.command)window.selectionCommands.push(d.command);super.send(data);}};`});
  }});
  await page.waitFor('document.body.dataset.entryRoute==="roster"');await page.click('#entry-enter-world');
  await page.waitFor('document.body.dataset.rigState==="ready"&&document.body.dataset.environmentState==="ready"&&JSON.parse(document.body.dataset.gameRemotePlayers||"[]").some(p=>p.id==="selection-companion")');
  check(await page.evaluate('JSON.parse(document.body.dataset.selectedUnit)===null'),'Entering town starts without an arbitrary enemy target');
  check(await page.evaluate('!document.querySelector(\'[data-overhead-name="player:selection-viewer"]\') && !document.getElementById("show-own-name").checked'),'Own overhead name defaults hidden');
  await page.waitFor('document.querySelector(\'[data-overhead-name="player:selection-companion"]\')?.hidden===false');
  await page.click('[data-overhead-name="player:selection-companion"]');
  await page.waitFor('document.getElementById("target-frame").dataset.kind==="player"&&document.getElementById("target-frame").dataset.targetId==="selection-companion"');
  check(await page.evaluate('document.getElementById("target-frame").dataset.health==="70"&&document.querySelector("#target-frame .unit-frame-name").textContent==="Mira"'),'Friendly name and current health appear');
  check(await page.evaluate('document.querySelector("#target-frame .unit-frame-image").src.endsWith("mage.webp")'),'Friendly frame uses class portrait');
  check(await page.evaluate('!document.getElementById("combat-stamina")'),'Separate centered stamina bar is absent');
  check(await page.evaluate('document.querySelector("#player-frame .unit-frame-level").textContent===String(window.selectionState.snapshot.progression.level)&&!document.querySelector("#player-frame .unit-frame-level").hidden'),'Player medallion shows actual level');
  check(await page.evaluate(`['player-frame','target-frame'].every(id=>{const root=document.getElementById(id),portrait=root.querySelector('.unit-frame-portrait'),health=root.querySelector('.unit-frame-health'),stamina=root.querySelector('.unit-frame-stamina');return getComputedStyle(portrait).borderRadius==='50%'&&health.clientHeight>=20&&!stamina.hidden&&stamina.clientHeight<health.clientHeight;})`),'Player and allied frames have circular portraits, larger health and thinner stamina');
  check(await page.evaluate('document.querySelector("#player-frame .unit-frame-stamina").getAttribute("aria-valuenow")===String(window.selectionState.snapshot.player.stamina)&&document.querySelector("#target-frame .unit-frame-stamina").getAttribute("aria-valuenow")===String(window.selectionState.players.find(p=>p.id==="selection-companion").player.stamina)'),'Both frames show current stamina');
  check(await page.evaluate('document.querySelector(\'.adventure-actions [data-action="strike"]\').disabled'),'Attack is disabled for friendly targets');
  const strikes=await page.evaluate<number>('window.selectionCommands.filter(c=>c.type==="action"&&c.action==="strike"&&c.pressed).length');
  await page.press('Digit1');
  check(await page.evaluate<number>('window.selectionCommands.filter(c=>c.type==="action"&&c.action==="strike"&&c.pressed).length')===strikes,'Attack key sends no strike against the prior enemy');
  bot.send(JSON.stringify({type:'command',sequence:++botSequence,command:{type:'action',action:'rest',pressed:true}}));
  bot.send(JSON.stringify({type:'command',sequence:++botSequence,command:{type:'action',action:'rest',pressed:false}}));
  await page.waitFor('document.getElementById("target-frame").dataset.health==="100"');
  await page.shot('friendly-name-health-and-portrait');
  await page.press('Tab');
  await page.waitFor('document.getElementById("target-frame").dataset.kind==="enemy"&&JSON.parse(document.body.dataset.selectedUnit).kind==="enemy"');
  check(await page.evaluate('document.querySelector("#target-frame .unit-frame-stamina").hidden'),'Enemies without stamina have no invented energy');
  check(await page.evaluate('document.querySelector("#target-frame .unit-frame-level").textContent===String(window.selectionState.snapshot.threats.find(t=>t.id===document.getElementById("target-frame").dataset.targetId).level)'),'Mirrored enemy medallion shows actual level');
  await page.shot('classic-enemy-frame');
  await page.evaluate(`(async()=>{const {Scene,Vector3}=await import('three');Scene.prototype.onAfterRender=function(renderer,scene,camera){const root=this.children.find(o=>o.userData.playerId==='selection-companion');if(root){const p=root.position.clone().add(new Vector3(0,1.1,0)).project(camera),r=document.getElementById('world-canvas').getBoundingClientRect();window.companionPoint={x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2};}};})()`);
  await page.waitFor('window.companionPoint');
  const center=await page.evaluate<{x:number;y:number}>('window.companionPoint');
  let body:{x:number;y:number}|null=null;
  for(const dy of [0,-10,10,-20,20]){for(const dx of [0,-10,10]){
    const point={x:center.x+dx,y:center.y+dy};
    if(!await page.evaluate(`document.elementFromPoint(${point.x},${point.y})?.id==='world-canvas'`))continue;
    await page.call('Input.dispatchMouseEvent',{type:'mouseMoved',...point,buttons:0});await Bun.sleep(80);
    if(await page.evaluate('document.getElementById("world-canvas").dataset.hoverKind==="player"&&document.getElementById("world-canvas").dataset.hoverId==="selection-companion"')){body=point;break;}
  }if(body)break;}
  check(body,'Visible companion body is pickable');
  await page.call('Input.dispatchMouseEvent',{type:'mousePressed',...body,button:'left',buttons:1,clickCount:1});
  await page.call('Input.dispatchMouseEvent',{type:'mouseReleased',...body,button:'left',buttons:0,clickCount:1});
  await page.waitFor('document.getElementById("target-frame").dataset.kind==="player"&&document.getElementById("world-canvas").dataset.selectedPlayer==="selection-companion"');
  await page.shot('friendly-body-selection');
  await page.click('#pause-open');
  await page.click('#show-own-name');
  await page.press('Escape');
  await page.waitFor('document.querySelector(\'[data-overhead-name="player:selection-viewer"]\')?.hidden===false');
  check(await page.evaluate('localStorage.getItem("greywrought/show-own-name")==="true"'),'Own-name setting is saved');
  await page.click('[data-overhead-name="player:selection-viewer"]');
  await page.waitFor('document.getElementById("target-frame").dataset.targetId==="selection-viewer"');
  await page.click('[data-overhead-name="player:selection-companion"]');
  bot.close();
  await page.waitFor('JSON.parse(document.body.dataset.selectedUnit)===null&&document.querySelector(".unit-frame-target-group").hidden');
  await page.click('[data-overhead-name="player:selection-viewer"]');
  await page.key('KeyW',true);
  await page.waitFor('window.selectionState.snapshot.player.inCombat',15000);
  await page.key('KeyW',false);
  await page.waitFor('JSON.parse(document.body.dataset.selectedUnit)?.id==="scout"&&document.getElementById("target-frame").dataset.kind==="enemy"');
  check(await page.evaluate('window.selectionState.snapshot.threats.some(t=>t.id==="scout"&&t.targetPlayerId==="selection-viewer"&&t.aggro)'),'The newly selected enemy is attacking this player');
  await page.press('Escape');
  await page.waitFor('JSON.parse(document.body.dataset.selectedUnit)===null');
  const clearedTime=await page.evaluate<number>('window.selectionState.serverTime');
  await page.waitFor(`window.selectionState.serverTime>${clearedTime}+.5`);
  check(await page.evaluate('JSON.parse(document.body.dataset.selectedUnit)===null&&document.getElementById("pause-panel").hidden'),'Escape stays cleared while the same enemy attacks, without opening the menu');
  const clearedStrikes=await page.evaluate<number>('window.selectionCommands.filter(c=>c.type==="action"&&c.action==="strike"&&c.pressed).length');
  await page.press('Digit1');
  check(await page.evaluate<number>('window.selectionCommands.filter(c=>c.type==="action"&&c.action==="strike"&&c.pressed).length')===clearedStrikes,'A cleared target cannot attack the earlier enemy');
  await page.press('Tab');
  await page.waitFor('JSON.parse(document.body.dataset.selectedUnit)?.kind==="enemy"');
  await page.press('Escape');
  await page.waitFor('JSON.parse(document.body.dataset.selectedUnit)===null');
  await page.press('Escape');
  await page.waitFor('!document.getElementById("pause-panel").hidden');
  check(await page.evaluate('window.selectionState.session.mode==="shared"'),'Escape menu does not pause the world');
  await page.shot('escape-cleared-target');
  await page.click('#pause-tab-settings');
  await page.evaluate('document.getElementById("unit-frames-locked").scrollIntoView({block:"center"})');
  await page.click('#unit-frames-locked'); await page.press('Escape');
  const frameStart=await page.evaluate<{x:number,y:number}>('(() => {const r=document.getElementById("player-frame").getBoundingClientRect();return {x:r.x+30,y:r.y+30};})()');
  await page.call('Input.dispatchMouseEvent',{type:'mouseMoved',...frameStart,buttons:0});
  await page.call('Input.dispatchMouseEvent',{type:'mousePressed',...frameStart,button:'left',buttons:1,clickCount:1});
  await page.waitFor('document.getElementById("player-frame").classList.contains("unit-frame-dragging")');
  await page.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:frameStart.x-40,y:frameStart.y-80,button:'left',buttons:1});
  await page.evaluate('new Promise(resolve=>requestAnimationFrame(resolve))');
  await page.call('Input.dispatchMouseEvent',{type:'mouseReleased',x:frameStart.x-40,y:frameStart.y-80,button:'left',buttons:0,clickCount:1});
  check(await page.evaluate(`(() => {const p=document.getElementById('player-frame').getBoundingClientRect(),t=document.querySelector('.unit-frame-target-group').getBoundingClientRect();return Math.abs(p.x+30-(${frameStart.x}-40))<2&&Math.abs(p.y-t.y)<1&&Math.abs(p.x+t.x+p.width-innerWidth)<1;})()`),'Dragging larger frames preserves mirrored positions');
  const frameLayout=await page.evaluate<string>('localStorage.getItem("greywrought.adventure.unit-frames.v1")');
  check(JSON.parse(frameLayout).positions,'Dragged frame positions are saved');
  await page.shot('mirrored-frames');
  await page.reload();
  await page.waitFor('document.body.dataset.entryRoute==="roster"'); await page.click('#entry-enter-world');
  await page.waitFor('document.body.dataset.rigState==="ready"');
  check(await page.evaluate(`localStorage.getItem('greywrought.adventure.unit-frames.v1')===${JSON.stringify(frameLayout)}&&Math.abs(document.getElementById('player-frame').getBoundingClientRect().x+30-(${frameStart.x}-40))<2`),'Saved frame position is restored after reload');
  check(page.errors.length===0,'No browser exceptions');
  console.log('PASS unit frame appearance, live health/stamina, mirrored saved dragging, player selection, Escape clearing and Tab reselection',page.output);
} catch(error){await page?.shot('failure').catch(()=>{});console.error(await page?.evaluate('({state:window.selectionState,selected:document.body.dataset.selectedUnit,frame:document.getElementById("target-frame")?.outerHTML,point:window.companionPoint})').catch(()=>undefined));throw error;}
finally{bot.close();await page?.close();await service.close();server.stop(true);frontend.kill();await frontend.exited;}
