import { check, openBrowser } from './session.js';
Bun.env.GREYWROUGHT_DEBUG_PORT='9394';
const first=await openBrowser('shared-world-first');
Bun.env.GREYWROUGHT_DEBUG_PORT='9395';
const second=await openBrowser('shared-world-second');
try {
  await first.enter();
  await second.waitFor('["account","creator","roster"].includes(document.body.dataset.entryRoute)');
  await second.evaluate(`(() => {
    document.getElementById('entry-display-name').value='Companion';document.getElementById('entry-account-form').requestSubmit();
    document.querySelector('[data-entry-archetype="mage"]').click();
    document.getElementById('entry-character-name').value='Merlin';document.getElementById('entry-character-form').requestSubmit();
  })()`);
  await second.enter();
  await first.waitFor('JSON.parse(document.body.dataset.gameRemotePlayers).length===1');
  await second.waitFor('JSON.parse(document.body.dataset.gameRemotePlayers).length===1');
  check(await first.evaluate<boolean>(`[...document.querySelectorAll('.adventure-actions kbd')].map(e=>e.textContent).join(',')==='1,2,3,4,5,6,7,8,9,0,-,='`),'Hotbar must be numbered in keyboard order');
  check(await first.evaluate<number>(`document.querySelectorAll('.adventure-actions [data-action]:not(.action-locked)').length`)===3,'Starting bar must contain attack, block and the potion on equals');
  check(await first.evaluate<boolean>(`document.querySelector('[data-action="strike"] img').src.endsWith('sword-strike.png')`),'Warrior must retain sword');
  check(await second.evaluate<boolean>(`document.querySelector('[data-action="strike"] img').src.endsWith('wand-bolt.svg')`),'Mage must retain wand');
  check(await first.evaluate<boolean>(`document.querySelector('[data-action="brace"] .action-cost')===null`),'Ability icons must not have stamina badges');
  check(await first.evaluate<string>(`document.querySelector('[data-action="drinkPotion"] kbd').textContent`)==='=','Potion must be on equals');
  await first.press('Enter');
  const greeting='Hello shared world '+Date.now();
  await first.call('Input.insertText',{text:greeting});await first.press('Enter');
  await second.waitFor(`document.querySelector('#chat-log-messages').textContent.includes(${JSON.stringify('Wayfarer: '+greeting)})`);
  await first.press('Escape');
  await first.key('KeyD',true);await first.waitFor('Number(document.body.dataset.gamePlayerX)<-2');
  await first.click('#chat-log-input');await first.key('KeyD',false);
  await second.waitFor(`JSON.parse(document.body.dataset.gameRemotePlayers).some(p=>p.name==='Wayfarer'&&p.player.position.x<-2&&!p.player.moving)`);
  await first.press('Escape');
  await second.waitFor(`JSON.parse(document.body.dataset.gameRemotePlayers).some(p=>p.name==='Wayfarer'&&p.player.position.x<-2)`);
  check(Number((await second.read()).gamePlayerX)===0,'One player moving must not move the other');
  await first.shot('two-players-and-chat');
  await first.key('KeyA',true);await first.waitFor('Number(document.body.dataset.gamePlayerX)>-0.2');await first.key('KeyA',false);
  await first.key('KeyW',true);await first.waitFor('Number(document.body.dataset.gamePlayerZ)>2.5');await first.key('KeyW',false);
  await first.press('Digit2');
  await first.waitFor('Number(document.body.dataset.gameBlock)>0');
  check(await first.evaluate<boolean>('document.getElementById("combat-plan")===null'),'Turn planner must be absent');
  await first.key('KeyW',true);await first.waitFor('Number(document.body.dataset.gamePlayerZ)>8');await first.key('KeyW',false);
  await first.press('Digit1');
  await first.waitFor(`Number(document.querySelector('#map-threats [data-enemy-id="scout"]').dataset.health)<96`,20000);
  await first.press('Digit1');await first.waitFor('document.body.dataset.gameAutoAttack==="false"');
  const hp=await first.evaluate<string>(`document.querySelector('#map-threats [data-enemy-id="scout"]').dataset.health`);
  await second.waitFor(`document.querySelector('#map-threats [data-enemy-id="scout"]').dataset.health===${JSON.stringify(hp)}`);
  await second.shot('shared-enemy-damage');
  await first.evaluate('document.getElementById("return-roster").click()');
  await second.waitFor('JSON.parse(document.body.dataset.gameRemotePlayers).length===0');
  await first.click('#entry-enter-world');await first.waitFor('document.body.dataset.entryRoute==="world"&&document.body.dataset.gameOnline==="true"');
  await second.waitFor('JSON.parse(document.body.dataset.gameRemotePlayers).length===1');
  check(first.errors.length===0&&second.errors.length===0,'Both browsers must remain free of errors');
  console.log('PASS two players, distinct movement, shared chat and enemy damage, numbered abilities, immediate Block, repeating auto attack, rejoin; '+first.output);
} finally {await first.close();await second.close();}
