import { check, openBrowser } from './session.js';
Bun.env.GREYWROUGHT_DEBUG_PORT='9394';
const first=await openBrowser('shared-world-first');
Bun.env.GREYWROUGHT_DEBUG_PORT='9395';
const second=await openBrowser('shared-world-second');
const queue='JSON.parse(document.getElementById("combat-plan").dataset.queued)';
try {
  await first.enter();
  await second.waitFor('["account","creator","roster"].includes(document.body.dataset.entryRoute)');
  await second.evaluate(`(() => {
    document.getElementById('entry-display-name').value='Companion';document.getElementById('entry-account-form').requestSubmit();
    document.querySelector('[data-entry-archetype="mage"]').click();
    document.getElementById('entry-character-name').value='Merlin';document.getElementById('entry-character-form').requestSubmit();
  })()`);
  await second.enter();
  await first.waitFor('JSON.parse(document.body.dataset.gameRemotePlayers).length===1');
  await second.waitFor('JSON.parse(document.body.dataset.gameRemotePlayers).length===1');
  check(await first.evaluate<boolean>(`[...document.querySelectorAll('.adventure-actions kbd')].map(e=>e.textContent).join(',')==='1,2,3,4,5,6,7,8,9,0,-,='`),'Hotbar must be numbered in keyboard order');
  check(await first.evaluate<number>(`document.querySelectorAll('.adventure-actions [data-action]').length`)===3,'Starting bar must contain attack, block and the potion on equals');
  check(await first.evaluate<boolean>(`document.querySelector('[data-action="strike"] img').src.endsWith('sword-strike.png')`),'Warrior must retain sword');
  check(await second.evaluate<boolean>(`document.querySelector('[data-action="strike"] img').src.endsWith('wand-bolt.svg')`),'Mage must retain wand');
  await first.press('Enter');
  await first.call('Input.insertText',{text:'Hello shared world'});await first.press('Enter');
  await second.waitFor(`document.querySelector('#chat-log-messages').textContent.includes('Wayfarer: Hello shared world')`);
  await first.press('Escape');
  await first.key('KeyD',true);await first.waitFor('Number(document.body.dataset.gamePlayerX)<-2');await first.key('KeyD',false);
  await second.waitFor(`JSON.parse(document.body.dataset.gameRemotePlayers).some(p=>p.name==='Wayfarer'&&p.player.position.x<-2)`);
  check(Number((await second.read()).gamePlayerX)===0,'One player moving must not move the other');
  await first.shot('two-players-and-chat');
  await first.key('KeyA',true);await first.waitFor('Number(document.body.dataset.gamePlayerX)>-0.2');await first.key('KeyA',false);
  await first.key('KeyW',true);await first.waitFor('Number(document.body.dataset.gamePlayerZ)>2.5');await first.key('KeyW',false);
  await first.press('Digit2');await first.press('Digit1');await first.press('Digit1');
  await first.waitFor(queue+'.length===3');
  check(await first.evaluate<string>(queue+'.map(e=>e.action).join()')==='brace,strike,strike','Number keys must queue in first available order');
  await first.click('.combat-plan-move[data-offset="0"]');await first.press('Digit1');
  await first.waitFor(queue+'.every(e=>e.action==="strike")');
  await first.click('.combat-plan-move[data-offset="1"]');
  await first.waitFor('!document.querySelector(".adventure-actions [data-action=brace]").disabled');
  await first.click('.adventure-actions [data-action="brace"]');
  await first.waitFor(queue+'[1].action==="brace"');
  const pos=await first.evaluate<{x:number;y:number}>(`(()=>{const r=document.querySelector('.combat-plan-move[data-offset="2"]').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);
  await first.call('Input.dispatchMouseEvent',{type:'mousePressed',...pos,button:'right',buttons:2,clickCount:1});
  await first.call('Input.dispatchMouseEvent',{type:'mouseReleased',...pos,button:'right',buttons:0,clickCount:1});
  await first.waitFor(queue+'.length===2');
  await first.press('Digit1');await first.waitFor(queue+'.length===3');
  await first.shot('numbered-bar-queue-editing');
  await first.key('KeyW',true);await first.waitFor('Number(document.body.dataset.gamePlayerZ)>8');await first.key('KeyW',false);
  await first.press('Digit1');
  await first.waitFor(`Number(document.querySelector('#map-threats [data-enemy-id="scout"]').dataset.health)<96`,20000);
  const hp=await first.evaluate<string>(`document.querySelector('#map-threats [data-enemy-id="scout"]').dataset.health`);
  await second.waitFor(`document.querySelector('#map-threats [data-enemy-id="scout"]').dataset.health===${JSON.stringify(hp)}`);
  await second.shot('shared-enemy-damage');
  await first.evaluate('document.getElementById("return-roster").click()');
  await second.waitFor('JSON.parse(document.body.dataset.gameRemotePlayers).length===0');
  await first.click('#entry-enter-world');await first.waitFor('document.body.dataset.entryRoute==="world"&&document.body.dataset.gameOnline==="true"');
  await second.waitFor('JSON.parse(document.body.dataset.gameRemotePlayers).length===1');
  check(first.errors.length===0&&second.errors.length===0,'Both browsers must remain free of errors');
  console.log('PASS two players, distinct movement, shared chat and enemy damage, numbered two-ability bar, FIFO queue, mouse replacement/removal, rejoin; '+first.output);
} finally {await first.close();await second.close();}
