import type { AdventureSnapshot } from "../game/adventure-types.js";
import { publicUrl } from "./public-url.js";

export function createTradePanel(host: HTMLElement, callbacks: { onOffer(kind: "supplies" | "potions", quantity: number): void; onAccept(): void; onClose(): void }) {
  const panel = document.createElement("section"); panel.id = "trade-panel"; panel.hidden = true; panel.setAttribute("role", "dialog"); panel.setAttribute("aria-labelledby", "trade-title");
  panel.innerHTML = `<style>
  #trade-panel{position:absolute;z-index:45;left:50%;top:18%;transform:translateX(-50%);width:min(520px,calc(100% - 32px));border:3px ridge #79796f;border-radius:5px;background:linear-gradient(110deg,#242721,#111713 70%);color:#ddd3b9;box-shadow:0 8px 25px #0009,inset 0 0 16px #000;font:12px/1.4 system-ui;pointer-events:auto}
  #trade-panel[hidden]{display:none} #trade-panel .trade-columns{display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:14px 12px}.trade-col{border:1px solid #666c5a;padding:8px;min-height:120px;background:#0c140fcc}.trade-col h3{margin:0 0 8px;color:#e7ce87;font:15px Georgia}.trade-item{display:flex;align-items:center;gap:8px}.trade-item img{width:48px;height:48px;border:2px ridge #948669;border-radius:3px}.trade-item strong{display:block;font-weight:500}.trade-item small{display:block;color:#b9c2ad;margin-top:3px}.trade-controls{display:flex;align-items:center;gap:8px;margin-top:12px}.trade-controls button,#trade-accept,#trade-cancel{border:1px solid #77795f;background:#252c20;color:#eadbaf;padding:5px 10px;cursor:pointer}.trade-controls button:disabled,#trade-accept:disabled{opacity:.5;cursor:default}.trade-quantity{min-width:54px;text-align:center;color:#f0da8c;font-weight:600}.trade-status{padding:8px 12px;color:#b9c2ad;min-height:18px}.trade-footer{border-top:2px ridge #676d5e;padding:8px;text-align:right}.rpg-window-close{cursor:pointer}
  </style><header class="rpg-window-header"><h2 id="trade-title" class="rpg-window-title">Trade with Mara</h2><button id="trade-close" class="rpg-window-close" type="button" aria-label="Close trade">×</button></header>
  <div class="trade-columns"><div class="trade-col"><h3>You offer</h3><div class="trade-controls"><button id="trade-offer-supplies" type="button">Supplies</button><button id="trade-offer-potions" type="button">Potions</button></div><div class="trade-item"><img id="trade-offer-icon" alt=""><div><strong id="trade-offer-name"></strong><small id="trade-offer-detail"></small></div></div><div class="trade-controls"><button id="trade-less" type="button">−</button><span id="trade-quantity" class="trade-quantity">3</span><button id="trade-more" type="button">+</button></div></div>
  <div class="trade-col"><h3>Mara offers</h3><div class="trade-item"><img id="trade-receive-icon" alt=""><div><strong id="trade-receive-name"></strong><small id="trade-receive-detail"></small></div></div></div></div>
  <div id="trade-status" class="trade-status"></div><div class="trade-footer"><button id="trade-cancel" type="button">Cancel</button> <button id="trade-accept" type="button">Accept</button></div>`;
  const q = panel.querySelector<HTMLElement>("#trade-quantity")!, less = panel.querySelector<HTMLButtonElement>("#trade-less")!, more = panel.querySelector<HTMLButtonElement>("#trade-more")!, accept = panel.querySelector<HTMLButtonElement>("#trade-accept")!, close = panel.querySelector<HTMLButtonElement>("#trade-close")!, cancel = panel.querySelector<HTMLButtonElement>("#trade-cancel")!;
  const offerSupplies = panel.querySelector<HTMLButtonElement>("#trade-offer-supplies")!, offerPotions = panel.querySelector<HTMLButtonElement>("#trade-offer-potions")!; less.setAttribute("aria-label", "Offer fewer"); more.setAttribute("aria-label", "Offer more");
  let current: AdventureSnapshot["trade"] = null;
  let renderedKey = "";
  const adjust = (delta: number) => { if (!current) return; callbacks.onOffer(current.kind, current.quantity + delta * current.step); };
  less.addEventListener("click", () => adjust(-1)); more.addEventListener("click", () => adjust(1)); offerSupplies.addEventListener("click", () => callbacks.onOffer("supplies", 3)); offerPotions.addEventListener("click", () => callbacks.onOffer("potions", 1)); accept.addEventListener("click", callbacks.onAccept); close.addEventListener("click", callbacks.onClose); cancel.addEventListener("click", callbacks.onClose); host.append(panel);
  return { update(snapshot: AdventureSnapshot) { current = snapshot.trade; panel.hidden = !current; if (!current) { renderedKey = ""; return; } const key = `${current.kind}:${current.quantity}:${current.receivedQuantity}:${current.available}:${current.canAccept}:${current.reason}`; if (key === renderedKey) return; renderedKey = key; const offerName = current.kind === "supplies" ? "Supplies" : "Health potion"; const receiveName = current.kind === "supplies" ? "Health potion" : "Supplies"; const offerIcon = current.kind === "supplies" ? "assets/ui/icons/items/treasure-chest.png" : "assets/ui/icons/items/health-potion-red.png"; const receiveIcon = current.kind === "supplies" ? "assets/ui/icons/items/health-potion-red.png" : "assets/ui/icons/items/treasure-chest.png"; const oi=panel.querySelector<HTMLImageElement>("#trade-offer-icon")!,ri=panel.querySelector<HTMLImageElement>("#trade-receive-icon")!; const os=publicUrl(offerIcon),rs=publicUrl(receiveIcon); if(oi.src!==os) oi.src=os; if(ri.src!==rs) ri.src=rs; panel.querySelector("#trade-offer-name")!.textContent = offerName; panel.querySelector("#trade-receive-name")!.textContent = receiveName; q.textContent = String(current.quantity); panel.querySelector("#trade-offer-detail")!.textContent = `Available: ${current.available}`; panel.querySelector("#trade-receive-detail")!.textContent = `Quantity: ${current.receivedQuantity}`; panel.querySelector("#trade-status")!.textContent = current.reason; less.disabled = current.quantity <= current.step; more.disabled = current.quantity + current.step > current.available; accept.disabled = !current.canAccept; }, dispose() { panel.remove(); } };
}
